### ISSUE TITLE
Kernel panic: task[0] trying to sleep

### ISSUE THREAD

**Issue by Weihnachtsmannn** [kalamangga-net/linux-1.0#3]
Hi, it's a great honor to meet you, Github.
There is a serious problem when I configure bochs startup, but I don't know how to fix it

The questions are as follows:
VFS: Insert root floppy and press ENTER
Kernel panic: task[0] trying to sleep
In swapper task - not syncing

Looking forward to your reply

**Comment by Anonymous941** [comment]
I'm confused...  Why did you react with a confused emoji to your own comment?  And what is this about?
